-- CreateTable
CREATE TABLE "dados_banco" (
    "id" SERIAL NOT NULL,
    "nr_inst" INTEGER NOT NULL,
    "nr_agencia" INTEGER NOT NULL,
    "cd_cliente" VARCHAR(255) NOT NULL,
    "nm_cliente" VARCHAR(100) NOT NULL,
    "nr_cpf_cnpj" VARCHAR(50) NOT NULL,
    "nr_contrato" INTEGER NOT NULL,
    "dt_contrato" TIMESTAMP(3) NOT NULL,
    "qt_prestacoes" INTEGER NOT NULL,
    "vl_total" VARCHAR(15) NOT NULL,
    "cd_produto" INTEGER NOT NULL,
    "ds_produto" VARCHAR(100) NOT NULL,
    "cd_carteira" INTEGER NOT NULL,
    "ds_carteira" VARCHAR(100) NOT NULL,
    "nr_proposta" INTEGER NOT NULL,
    "nr_presta" INTEGER NOT NULL,
    "tp_presta" VARCHAR(50) NOT NULL,
    "nr_seq_pre" INTEGER NOT NULL,
    "dt_vct_pre" TIMESTAMP(3) NOT NULL,
    "vl_presta" VARCHAR(15) NOT NULL,
    "vl_mora" VARCHAR(15) NOT NULL,
    "vl_multa" VARCHAR(15) NOT NULL,
    "vl_out_acr" VARCHAR(15) NOT NULL,
    "vl_iof" VARCHAR(15) NOT NULL,
    "vl_desconto" VARCHAR(15) NOT NULL,
    "vl_atual" VARCHAR(15) NOT NULL,
    "id_situac" VARCHAR(100) NOT NULL,
    "id_sit_venc" VARCHAR(100) NOT NULL,

    CONSTRAINT "dados_banco_pkey" PRIMARY KEY ("id")
);
