export type Bank = {
    id: number,
    nr_inst: number,
    nr_agencia: number,
    cd_cliente: string,
    nm_cliente: string,
    nr_cpf_cnpj: string,
    nr_contrato: number,
    dt_contrato: Date,
    qt_prestacoes: number,
    vl_total: string,
    cd_produto: string,
    ds_produto: string,
    cd_carteira: number,
    ds_carteira: string,
    nr_proposta: number,
    nr_presta: number,
    tp_presta: string,
    dt_vct_pre: Date, 
    vl_presta: string,   
    vl_mora: string,   
    vl_multa: string,  
    vl_out_acr: string,  
    vl_iof: string,  
    vl_desconto: string,  
    vl_atual: string,  
    id_situac: string,
    id_sit_venc: string

}