export type Bank = {
    id: number,
    nrInst: number,
    nrAgencia: number,
    cdCliente: string,
    nmCliente: string,
    nrCpfCnpj: string,
    nrContrato: number,
    dtContrato: Date,
    qtPrestacoes: number,
    vlTotal: string,
    cdProduto: string,
    dsProduto: string,
    cdCarteira: number,
    dsCarteira: string,
    nrProposta: number,
    nrPresta: number,
    tpPresta: string,
    nrSeqPre: number,
    dtVctPre: Date, 
    vlPresta: string,   
    vlMora: string,   
    vlMulta: string,  
    vlOutAcr: string,  
    vlIof: string,  
    vlDescon: string,  
    vlAtual: string,  
    idSituac: string,
    idSitVenc: string

}